#!/bin/bash
# openshift-snapshot 0.1
#
# Usage: openshift-snapshot OPENSHIFT-SSH-URL
#
# Restore using rhc:
# rhc snapshot restore -a {appName} -f {/path/to/snapshot/appName.tar.gz}
#
# Restore using ssh:
# cat 'backup.tar.gz' | ssh OPENSHIFT-SSH-URL 'restore INCLUDE_GIT'
#
# openshift-snapshot home page: <http://github.com/mattias-ohlsson/openshift-snapshot/>.

# Get the ssh url 
sshurl=$1

# Get the hostname
appurl=$(echo $sshurl | sed 's|.*@||')

# Echo hostname
echo $appurl 1>&2

# Create the snapshot
ssh $sshurl 'snapshot' > $appurl-$(date --iso-8601).tar.gz
